In [43]:
#first we given data is 

import numpy as np
list=['1','2','3','4','5']
array_list=np.array(object=list)

In [44]:
type(list)

list

In [50]:
type(array_list)

numpy.ndarray

In [46]:
#list and array are very different because 
list contain multiple data type element in a list 
list are mutable 
list inside a list can be created 
list are the one type of data in python

array is a special type of data structure 
array is group of variable 
array is a linear collection of similar element
we can access the element by single subscript
arr[0] 
array contain only similar type of element 

SyntaxError: invalid syntax (2817261851.py, line 2)

In [47]:
#Answer_2

#first we find data type of all element in list variable
for i in list:
    print(type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [51]:
#now we find the data type of all element in array_list
for i in array_list:
    print(type(i))

<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In [34]:
#Answer_3

#some changes of array_list
array_list = np.array(object = list, dtype = int)

In [35]:
array_list

array([1, 2, 3, 4, 5])

In [37]:
#data type of variable list elements
for i in list:
    print(type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [41]:
#data type of array_list elements
for i in array_list:
    print(i.dtype)

int64
int64
int64
int64
int64


In [ ]:
#both have different data type because list contain string type elements 
# and array_list contain the integer type element so we can not perform mathematics operation on string element

In [52]:
#Answer_4

#given that 

import numpy as np
num_list = [[1,2,3],[4,5,6]]
num_array = np.array(object = num_list)

In [61]:
#first we check our num_array
num_array
#num_array is a 2_D array 

array([[1, 2, 3],
       [4, 5, 6]])

In [57]:
#i)shape 
np.shape(num_array)

#it indicates that the which is the shape of the array it means 
#how many row and column are present in array 
#   2 - it shows that 2 row present in array
#   3 - it shows that 3 column are present in array 


(2, 3)

In [59]:
#ii)size
np.size(num_array)

#this method is indicated the how many elements are present in the array
#so six elements are present in the array 


6

In [62]:
#Answer_5

#if we create a array first we import the numpy library
import numpy as np 
arr=np.zeros((3,3))
arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [63]:
#as a see that shape of array is (3,3) but we can check it 
np.shape(arr)

(3, 3)

In [64]:
#and we can check the  size of array
np.size(arr)

9

In [65]:
#Answer_6

import numpy as np
identity_matrix=np.eye(5)
identity_matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [66]:
#shape of the array
np.shape(identity_matrix)

(5, 5)

In [67]:
np.size(identity_matrix)

25